### ISSUE TITLE
horizon.height is broken

### ISSUE THREAD

**Issue by sujpdo** [BigFatDog/cubism-es#2]
## Expected Behavior
`horizon.height([pixels])` should set the horizon height when passed a value.

## Current Behavior
The height remains 30px.

## Steps to Reproduce
1. Open one of the demos of the repository, like stock.html or simple.html
2. Change the height of a horizon chart:
`context.horizon(d3.selectAll(".horizon")).height(120)`

**Comment by BigFatDog** [comment]
[Version 1.1.0 ](https://github.com/BigFatDog/cubism-es/releases/tag/1.1.0) has been released to fix this bug.
